name: nitoons
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  mime: ^1.0.0
  dotted_border: ^2.0.0+2
  open_file: ^3.2.1
  stacked_services: ^1.4.0
  get_it: ^7.1.3
  pmvvm: ^4.0.1
  cached_network_image: ^3.0.0
  pinput: ^4.0.0
  intl_phone_field: ^3.2.0

  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  auto_size_text: ^3.0.0
  syncfusion_flutter_datepicker: ^25.1.39
  video_thumbnail: ^0.5.3
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  video_player: ^2.8.5
  riverpod: ^2.5.1
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^9.2.0
  hooks_riverpod: ^2.5.1
  camera: ^0.10.5+9
  path_provider: ^2.1.3
  path: ^1.9.0
  tutorial_coach_mark: ^1.2.11
  http: 1.2.1
  fluttertoast: ^8.2.5
  file_picker: ^8.0.3
  firebase_core: ^2.31.0
  flutter_hooks: ^0.18.3
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  firebase_messaging: ^14.9.4
  timeago: ^3.6.1
  socket_io_client: ^2.0.3+1
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  firebase_analytics: ^10.10.7
  flutter_emoji: ^2.5.1
  http_parser: ^4.0.2
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  visibility_detector: ^0.4.0+2
dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/applogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/png/applogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/png/applogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/png/applogo.png"


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/
    - assets/png/
    - assets/video/
    - assets/jpeg/

  fonts:
  - family: Satoshi
    fonts:
      - asset: assets/fonts/Satoshi-Regular.otf
        weight: 400
      - asset: assets/fonts/Satoshi-Medium.otf
        weight: 600
      - asset: assets/fonts/Satoshi-Bold.otf
        weight: 700


