import 'package:flutter_riverpod/src/consumer.dart';
import 'package:get_it/get_it.dart';
import 'package:nitoons/UI Actor/edit-profile/edit-profile_viewmodel.dart';
import 'package:nitoons/UI Actor/headshots/headshot_viewmodel.dart';
import 'package:nitoons/UI Actor/password setup/password_setup_viewmodel.dart';
import 'package:nitoons/UI Actor/phone number/phone_number_viewmodel.dart';
import 'package:nitoons/UI Actor/pin verification/pin_verification_viewmodel.dart';
import 'package:nitoons/UI Actor/project/project_view_model.dart';
import 'package:nitoons/UI Actor/role/page-one/role_viewmodel.dart';
import 'package:nitoons/UI Actor/role/page-two/name_page_viewmodel.dart';
import 'package:nitoons/UI Actor/role/signup_role_viewmodel.dart';
import 'package:nitoons/UI Actor/settings/settings_viewmodel.dart';
import 'package:nitoons/UI%20Actor/account_setup/account_setup_vm.dart';
import 'package:nitoons/data/app_storage.dart';

import 'UI Actor/actor_lookalikes/actorlookalike_viewmodel.dart';
import 'UI Actor/actor_profile_viewmodel.dart';
import 'UI Actor/awards/awards_vm.dart';
import 'UI Actor/edit_actor_profile/edit_actor_profile_viewmodel.dart';
import 'UI Actor/email_address_signUp/email_address_signup_viewmodel.dart';
import 'UI Actor/headshot/headshot_vm.dart';
import 'UI Actor/headshot/sideshot_vm.dart';
import 'UI Actor/height/height_vm.dart';
import 'UI Actor/language/language_vm.dart';
import 'UI Actor/link_to_reels/link_to_reels_vm.dart';
import 'UI Actor/location/location_viewmodel.dart';
import 'UI Actor/other_skills/other_skills_vm.dart';
import 'UI Actor/preferred_roles/preferred_roles_viewmodel.dart';
import 'UI Actor/profile/profile_view_model.dart';
import 'UI Actor/post/upload_post_viewmodel.dart';
import 'UI Actor/profile_picture/profile_picture_viewmodel.dart';
import 'UI Actor/project_done_section/project_done_viewmodel.dart';
import 'UI Actor/role/education-page-viewmodel.dart';
import 'UI Producer/ProducerMessageSettings/producer_message_settings_viewmodel.dart';
import 'UI Producer/add_monologues_to_role/add_monologues_to_role_update_vm.dart';
import 'UI Producer/add_monologues_to_role/add_monologues_to_role_vm.dart';
import 'UI Producer/age_acct_update/age_update_viewmodel.dart';
import 'UI Producer/choose_a_project/choose_a_project_vm.dart';
import 'UI Producer/choose_role/choose_role_vm.dart';
import 'UI Producer/create_roles/create_roles_vm.dart';
import 'UI Producer/edit_profile/age_edit_section/age_edit_viewmodel.dart';
import 'UI Producer/edit_profile/awards_edit_section/awards_edit_viewmodel.dart';
import 'UI Producer/edit_profile/company_info/company_info_edit_viewmodel.dart';
import 'UI Producer/edit_profile/company_location_edit.dart/company_location_edit_viewmodel.dart';
import 'UI Producer/edit_profile/education_edit_section/education_edit_viewmodel.dart';
import 'UI Producer/edit_profile/filmmaker_profile_edit_section.dart/filmmaker_profile_edit_viewmodel.dart';
import 'UI Producer/edit_profile/gender_edit_section/gender_edit_viewmodel.dart';
import 'UI Producer/edit_profile/height_edit_section/height_edit_viewmodel.dart';
import 'UI Producer/edit_profile/language_edit_section/language_edit_viewmodel.dart';
import 'UI Producer/edit_profile/recent_project_section/recent_project_viewmodel.dart';
import 'UI Producer/gender_acct_update/gender_update_viewmodel.dart';
import 'UI Producer/producer casting applicant/producer_casting_applicants_viewmodel.dart';
import 'UI Actor/login-phoneNumber/login_phonenumber_viewmodel.dart';
import 'UI Actor/login_email Address/login_email_address_viewmodel.dart';
import 'UI Producer/producer monologue/producers_monologues_roles_viewmodel.dart';
import 'UI Producer/producer rate and review page/producer_rate_review_viewmodel.dart';
import 'UI Producer/producerSettings/settings_viewmodel.dart';
import 'UI Producer/producer_nav_screens/producer_projects/producer_projects_vm.dart';
import 'UI Producer/producer_profile_details/producer_profile_vm.dart';
import 'UI Producer/project/producer_project_overview_viewmodel.dart';
import 'UI Producer/project/producer_project_viewmodel.dart';
import 'UI Producer/project_casting_period/producer_monologue_casting_time_viewmodel.dart';
import 'UI Producer/project_details/producer_project_details_viewmodel.dart';
import 'UI Producer/update_create_roles/create_roles_update_viewmodel.dart';
import 'UI Producer/update_producer_create_monologue/producer_update_create_monologue_viewmodel.dart';
import 'UI Producer/update_project_details/producer_project_update_viewmodel.dart';
import 'data/api_layer.dart';

GetIt locator = GetIt.instance;

Future<void> setupLocator() async {
  // locator.registerLazySingleton(() => SignupViewModel());
  locator.registerLazySingleton(() => HeadshotVm());
 locator.registerLazySingleton(() => SideshotVm());
  locator.registerLazySingleton(() => PhoneNumberViewmodel());
  locator.registerLazySingleton(() => PinVerificationViewmodel());
  locator.registerLazySingleton(() => PasswordSetupViewModel());
  locator.registerLazySingleton(() => LoginPhoneNumberViewModel());
  locator.registerLazySingleton(() => LoginEmailAddressViewmodel());
  locator.registerLazySingleton(() => SignUpRoleViewmodel());
  locator.registerLazySingleton(() => NamePageViewModel());
  locator.registerLazySingleton(() => ProfilePictureViewmodel());
  // locator.registerLazySingleton(() => RoleViewModel());
  locator.registerLazySingleton(() => HeadshotViewmodel());
  // locator.registerLazySingleton(() => ProjectPageViewModel());
  locator.registerLazySingleton(() => EditProfileViewmodel());
   locator.registerLazySingleton(() => ChooseRoleViewModel());
   //locator.registerLazySingleton(() => ProducerProfileVm());
  locator.registerLazySingleton(() => settingsViewmodel());
  locator.registerLazySingleton(() => ProducerProjectViewmodel());
  // locator.registerLazySingleton(() => ProducerEndorseRateAndReviewViewmodel());
  locator.registerLazySingleton(() => ProducerMonologueRolesviewmodel());
  locator.registerLazySingleton(() => ProducerCastingApplicantViewmodel());
  locator.registerLazySingleton(() => ProducerSettingsViewmodel());
  locator.registerLazySingleton(() => ProducerMessageSettingsViewmodel());
  locator.registerLazySingleton(() => ProducerRateAndReviewViewmodel());
  locator.registerLazySingleton(() => ProfileViewModel());
  locator.registerLazySingleton(() => EmailAddressSignUpViewmodel());
  locator.registerLazySingleton(() => ActorUploadPostViewmodel());
  locator.registerLazySingleton(() => ApiLayer());
  locator.registerLazySingleton(() => SharedPreferencesHelper());
  locator.registerLazySingleton(() => SecureStorageHelper());
  locator.registerLazySingleton(() => AccountSetupViewModel());
  locator.registerLazySingleton(() => OtherSkillsViewModel());
  locator.registerLazySingleton(() => ProducerProjectsViewModel());
  locator.registerLazySingleton(() => ProducerProjectDetailsViewmodel());
  locator.registerLazySingleton(() => CreateRolesViewModel());
  locator.registerLazySingleton(() => ProducerAddMonologuesToRoleViewModel());
  locator.registerLazySingleton(() => EducationPageViewmodel());
  locator.registerLazySingleton(() => LanguageScreenViewModel());
  locator.registerLazySingleton(() => ActorProfileViewmodel());
  locator.registerLazySingleton(() => EditActorProfileViewmodel());
  locator.registerLazySingleton(() => ActorlookalikeViewModel());
    locator.registerLazySingleton(() => ChooseAProjectViewModel());
//edit profile
locator.registerLazySingleton(() => AgeEditViewmodel());
locator.registerLazySingleton(() => AwardsEditViewmodel());
locator.registerLazySingleton(() => CompanyInfoEditViewmodel());
locator.registerLazySingleton(() => CompanyLocationEditViewmodel());
locator.registerLazySingleton(() => EducationEditViewmodel());
locator.registerLazySingleton(() => FilmmakerProfileEditViewmodel());
locator.registerLazySingleton(() => GenderEditViewmodel());
locator.registerLazySingleton(() => HeightEditViewmodel());
locator.registerLazySingleton(() => LanguageEditViewmodel());
locator.registerLazySingleton(() => RecentProjectViewmodel());
locator.registerLazySingleton(() => ProjectDoneViewmodel());
//account setup
locator.registerLazySingleton(() => AwardsVm());
locator.registerLazySingleton(() => GenderUpdateViewmodel());
locator.registerLazySingleton(() => AgeUpdateViewmodel());
//update project
locator.registerLazySingleton(() => ProducerProjectUpdateViewmodel());
locator.registerLazySingleton(() => ProducerMonologueCastingTimeViewmodel());
locator.registerLazySingleton(() => ProducerProjectOverviewViewmodel());
locator.registerLazySingleton(() => CreateRolesUpdateViewmodel());

locator.registerLazySingleton(() => ProducerUpdateCreateMonologueViewmodel());
locator.registerLazySingleton(() => ProducerAddMonologuesToRoleUpdateViewModel());
locator.registerLazySingleton(() => PreferredRolesViewModel());
locator.registerLazySingleton(() => LocationViewmodel());
locator.registerLazySingleton(() => HeightScreenViewModel());
locator.registerLazySingleton(() => LinkToReelsViewModel());



}
